
plugins {
	java
	id("org.springframework.boot") version "3.5.0"
	id("io.spring.dependency-management") version "1.1.7"

	// jib
	id("com.google.cloud.tools.jib") version "3.4.5"

}

group = "com.example"
version = "0.0.1-SNAPSHOT"

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom(configurations.annotationProcessor.get())
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation("org.springframework.boot:spring-boot-starter-web")
	compileOnly("org.projectlombok:lombok")
	annotationProcessor("org.projectlombok:lombok")
	testImplementation("org.springframework.boot:spring-boot-starter-test")
	testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

tasks.withType<Test> {
	useJUnitPlatform()
}



jib {


	from {
		image = "196648750246.dkr.ecr.ap-northeast-2.amazonaws.com/air-bss/base-image:latest"

		auth {
			username = "AWS"
			password = "eyJwYXlsb2FkIjoiOEMzMzNwekJ0UkhlWUNOaHpVNzFBSFYxOWlxNjdPMUd3ajZ1YTFwZWdVd2ZhVHFpeEp1RFM1UXRmR0QzYW8xWDBZZTJXZDRxVTJ3Y0tRM0hpdzlaSUJLTlNlNitmMHp6UUZURHphUkM0ZXBCZjY1WVlEbHo0NmxucE1uSnk5YzlUc1VHaTN3NDFlY0Q5NHpmQWZnbk13SHY3WHVBUmw1L2tBODZmTHZpR01CczdpZzJvREkwYkpzMFZhejFRUnBPbkUrYW84cFNwOGZZaWxVbUJMbCtxcExNK2s5N1JlNXZnQjk5YzdHWC9hajRCZTVvamxGZUtiK2UzYTNvelNNUFN6UzVXakkxYzVUd051aXFsQzVoZFVQVytsa1hSSkVLS3dSNG1zcHQ4ZEhwL09oc2JvY245ZFNoWTNLSktjWkRPWXUvSWJpTzdDMS9od1Z6a0NtVVhhaVZ5TE9ZcTl5Z2xUN1NwUmtTV2ltbTZnc2ZXWVNwWFJJL09Kbm9ycUc1cXQxNFZUek9GMGdnY1dlMUJQakhCMlBlbnJOTm5zcy9wWm1takJPNHVrY3pkdGZYQ21kazdtQlZEbjk1Q3RxdkFWNHo3c0d2S2hNWXBoUlhvMzBjOSttdXc2aWpoUTBQWVNMSk9sUy9yL2U5SnpXSTM1cnlORW53amFydm1SSDlIeGJRcTBCdTBVVXJHWlY2TUIwUDhPNS9Hd3VCNTVDUmkzdGhOL2l0aGNXQ3VtOVRJVEY4SnJNK3NmOGdvdUhiclQyWHdqTkIySGFpU1pSWkhucy94Y2xsSXJCOEtlcXFhT3FEcEFIbFQ1MXpGZlExbmFKNmRnY3JkRTBpMlZNbzBqK3RqRGhjUHhOS0FBcy9lZUpyT3ZsRHYxN21vQVJsU3Rtd0pHQVV6WEpkL3pGSllBeERSVVd0VVNQMHFLQndNL1QwbCtDRENSTi9qVzBDbG8wSlJCbUR1QWpLK2RPRkhZcHZjc1FCaW1oaFdLMFkwdml2NnlpN0phcDhaS0g0NVM3MjNHK096TG5DcFlRYTZFTXdXdUJIbmtGTWFkNE5BL3NjamwvTmRxcUJxb2ZhSjU3YmNaRlE1SjVxQWw4M1kxM25nRnpBY2FBTDNYcmdEOUpqREF6a1o3aFJ5V1FHQnozRk1mZ0NRZGxta2dBR1RncFplblU3a1VBY1UwTlFoeVdZczJ1dFZqaWJtV2JNQ2ExVlVSRDNCNWJ1QTRJaWtPNGFCcERkMlNjQTd0TTM1czgyQWE4WHIxRExGaE9meW5RZTcrdkJmWDVNeHQvQXpUVnB6ZnNUREtvd2VZZ0NNZUhtdDhudG03OUs0bUYwVzk3MjNhdERUMEZJUThCSVNKVlduREFLRWYxNyIsImRhdGFrZXkiOiJBUUlCQUhoQU9zYVcyZ1pOMDlXTnROR2tZYzhxcDExeFNoWi9kckVFb3kxSGs4TFhXZ0hxNTFJR2VZc0Fna1g1VG9ySjhFc3dBQUFBZmpCOEJna3Foa2lHOXcwQkJ3YWdiekJ0QWdFQU1HZ0dDU3FHU0liM0RRRUhBVEFlQmdsZ2hrZ0JaUU1FQVM0d0VRUU14M2d2VFVUQWFOa0NFSlZYQWdFUWdEdkthb0NBVGtTMTRyTnh2WWxCTVdtVE8rMm55Y3J6Yyt2NGVWeDduRlRYYzgzMDdJa3Y4elE1TGNKRnpYRS82R1lWK1RiTThtN2wxMWVoYlE9PSIsInZlcnNpb24iOiIyIiwidHlwZSI6IkRBVEFfS0VZIiwiZXhwaXJhdGlvbiI6MTc0OTc0NTU1MX0="

		}

	}
	to {
		image = "196648750246.dkr.ecr.ap-northeast-2.amazonaws.com/air-bss/air-bss-admin-center-api:latest"

		auth {
			username = "AWS"
			password = "eyJwYXlsb2FkIjoiOEMzMzNwekJ0UkhlWUNOaHpVNzFBSFYxOWlxNjdPMUd3ajZ1YTFwZWdVd2ZhVHFpeEp1RFM1UXRmR0QzYW8xWDBZZTJXZDRxVTJ3Y0tRM0hpdzlaSUJLTlNlNitmMHp6UUZURHphUkM0ZXBCZjY1WVlEbHo0NmxucE1uSnk5YzlUc1VHaTN3NDFlY0Q5NHpmQWZnbk13SHY3WHVBUmw1L2tBODZmTHZpR01CczdpZzJvREkwYkpzMFZhejFRUnBPbkUrYW84cFNwOGZZaWxVbUJMbCtxcExNK2s5N1JlNXZnQjk5YzdHWC9hajRCZTVvamxGZUtiK2UzYTNvelNNUFN6UzVXakkxYzVUd051aXFsQzVoZFVQVytsa1hSSkVLS3dSNG1zcHQ4ZEhwL09oc2JvY245ZFNoWTNLSktjWkRPWXUvSWJpTzdDMS9od1Z6a0NtVVhhaVZ5TE9ZcTl5Z2xUN1NwUmtTV2ltbTZnc2ZXWVNwWFJJL09Kbm9ycUc1cXQxNFZUek9GMGdnY1dlMUJQakhCMlBlbnJOTm5zcy9wWm1takJPNHVrY3pkdGZYQ21kazdtQlZEbjk1Q3RxdkFWNHo3c0d2S2hNWXBoUlhvMzBjOSttdXc2aWpoUTBQWVNMSk9sUy9yL2U5SnpXSTM1cnlORW53amFydm1SSDlIeGJRcTBCdTBVVXJHWlY2TUIwUDhPNS9Hd3VCNTVDUmkzdGhOL2l0aGNXQ3VtOVRJVEY4SnJNK3NmOGdvdUhiclQyWHdqTkIySGFpU1pSWkhucy94Y2xsSXJCOEtlcXFhT3FEcEFIbFQ1MXpGZlExbmFKNmRnY3JkRTBpMlZNbzBqK3RqRGhjUHhOS0FBcy9lZUpyT3ZsRHYxN21vQVJsU3Rtd0pHQVV6WEpkL3pGSllBeERSVVd0VVNQMHFLQndNL1QwbCtDRENSTi9qVzBDbG8wSlJCbUR1QWpLK2RPRkhZcHZjc1FCaW1oaFdLMFkwdml2NnlpN0phcDhaS0g0NVM3MjNHK096TG5DcFlRYTZFTXdXdUJIbmtGTWFkNE5BL3NjamwvTmRxcUJxb2ZhSjU3YmNaRlE1SjVxQWw4M1kxM25nRnpBY2FBTDNYcmdEOUpqREF6a1o3aFJ5V1FHQnozRk1mZ0NRZGxta2dBR1RncFplblU3a1VBY1UwTlFoeVdZczJ1dFZqaWJtV2JNQ2ExVlVSRDNCNWJ1QTRJaWtPNGFCcERkMlNjQTd0TTM1czgyQWE4WHIxRExGaE9meW5RZTcrdkJmWDVNeHQvQXpUVnB6ZnNUREtvd2VZZ0NNZUhtdDhudG03OUs0bUYwVzk3MjNhdERUMEZJUThCSVNKVlduREFLRWYxNyIsImRhdGFrZXkiOiJBUUlCQUhoQU9zYVcyZ1pOMDlXTnROR2tZYzhxcDExeFNoWi9kckVFb3kxSGs4TFhXZ0hxNTFJR2VZc0Fna1g1VG9ySjhFc3dBQUFBZmpCOEJna3Foa2lHOXcwQkJ3YWdiekJ0QWdFQU1HZ0dDU3FHU0liM0RRRUhBVEFlQmdsZ2hrZ0JaUU1FQVM0d0VRUU14M2d2VFVUQWFOa0NFSlZYQWdFUWdEdkthb0NBVGtTMTRyTnh2WWxCTVdtVE8rMm55Y3J6Yyt2NGVWeDduRlRYYzgzMDdJa3Y4elE1TGNKRnpYRS82R1lWK1RiTThtN2wxMWVoYlE9PSIsInZlcnNpb24iOiIyIiwidHlwZSI6IkRBVEFfS0VZIiwiZXhwaXJhdGlvbiI6MTc0OTc0NTU1MX0="

		}
	}

	container {
		creationTime = "USE_CURRENT_TIMESTAMP"  // 이걸 넣어야 빌드시간이 제대로 찍힘

		jvmFlags =
			listOf(
				"-Dserver.port=8080",
				"-Dfile.encoding=UTF-8",
				"-Djava.awt.headless=true"
			)

		ports = listOf("8080")

		// format = "OCI"
		mainClass = "com.example.demo.TestApplication"

		environment = mapOf(
			"SERVER_PORT" to (System.getenv("SERVER_PORT") ?: "8080")
		)

		creationTime = "USE_CURRENT_TIMESTAMP"
	}
}
